version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: ppcb2db
      POSTGRES_USER: ppcb2user
      POSTGRES_PASSWORD: ppcb2password

